import type { ResumeData } from "../types";

export const resume: ResumeData = {
  name: "Sarvesh Karandikar",
  title: "Software Engineer",
  tagline: "Backend & cloud infrastructure engineer at Cisco. Security, multi-cloud, and ML.",
  experience: [
    {
      role: "Software Engineer — Nexus Dashboard",
      company: "Cisco Systems",
      start: "2023-11",
      end: null,
      domains: ["security", "infra", "cloud"],
      tech: ["Java", "Go", "Kubernetes", "Postgres", "PKI"],
      bullets: [
        "Designed and implemented a Certificate Management System for automated root and intermediate CA creation, secure certificate signing, and integrity of Kubernetes-based communications.",
        "Enhanced external CA integration to securely onboard Cisco XE/XR devices, streamlining enterprise deployment and configuration.",
        "Developed an agent-based interface for Postgres and time-series DB management, enabling secure superuser access with application-specific flexibility.",
        "Implemented an SPI-based leader-election framework in Java for active-standby configurations with dynamic leader selection.",
      ],
    },
    {
      role: "Software Engineer — Cloud Network Controller",
      company: "Cisco Systems",
      start: "2020-07",
      end: "2023-10",
      domains: ["cloud", "security", "infra"],
      tech: ["Python", "Terraform", "GCP", "AWS", "Azure", "Dgraph"],
      bullets: [
        "Integrated Google Cloud Platform into the ACI model-based cloud networking solution, enabling multi-cloud compatibility and scalability.",
        "Enhanced a configuration-drift platform to detect security-group rule drift across L4–L7 service device chains, improving compliance checks.",
        "Built a centralized Terraform-based collection service aggregating multi-cloud config into a unified graph database.",
        "Created a firewall network-configuration analysis service using Binary Decision Diagrams to assess connectivity and traffic flows.",
      ],
    },
    {
      role: "Website Developer",
      company: "USC Global Supply Chain Management",
      start: "2019-04",
      end: "2020-05",
      domains: ["web"],
      tech: ["JavaScript", "HTML", "CSS"],
      bullets: [
        "Designed and continuously improved websites, including a redesign of a global supply-chain summit event site with sponsor management and full technical ownership.",
      ],
    },
    {
      role: "Software Engineer Intern",
      company: "Circle Link",
      start: "2019-05",
      end: "2019-08",
      domains: ["ml", "data"],
      tech: ["Python", "NLP", "Elasticsearch", "OCR"],
      bullets: [
        "Implemented Named Entity Recognition to classify entities in loan documents, enabling extraction and Elasticsearch indexing.",
        "Fine-tuned an OCR-to-PDF model to recognize MICR formats on checks, streamlining loan tracking.",
      ],
    },
  ],
  projects: [
    {
      id: "cifar-dcgan",
      title: "DCGAN Image Synthesis",
      blurb: "Deep Convolutional GAN generating high-quality images from noise, trained on CIFAR-10 with batch norm and adversarial training.",
      tech: ["TensorFlow", "Python"],
      domains: ["ml"],
      repo: "https://github.com/sarvesh1karandikar/cifar-dcgan",
      demo: true,
    },
    {
      id: "faq-chatbot",
      title: "Personalized FAQ Chatbot",
      blurb: "Local FAQ chatbot using LLaMA 2-7B to vectorize PDFs for real-time, context-aware question answering on a 12GB GPU.",
      tech: ["Python", "LLaMA", "RAG"],
      domains: ["ml"],
      demo: false,
    },
    {
      id: "satellite-road-detection",
      title: "Satellite Road Detection",
      blurb: "Classical computer-vision pipeline (morphology + K-means + edge detection) that highlights roads in satellite imagery.",
      tech: ["Computer Vision", "MATLAB"],
      domains: ["ml", "data"],
      repo: "https://github.com/sarvesh1karandikar/satellite-road-detection",
      demo: true,
    },
    {
      id: "lstm-text-generator",
      title: "LSTM Text Generator",
      blurb: "From-scratch NumPy RNN/LSTM that generates prose word-by-word; reaches ~90% next-word accuracy.",
      tech: ["NumPy", "Python"],
      domains: ["ml"],
      repo: "https://github.com/sarvesh1karandikar/lstm-text-generator",
      demo: true,
    },
    {
      id: "cifar-image-classifier",
      title: "CIFAR-10 Image Classifier",
      blurb: "Convolutional neural network classifying CIFAR-10 images at ~75% test accuracy.",
      tech: ["TensorFlow", "Python"],
      domains: ["ml"],
      repo: "https://github.com/sarvesh1karandikar/cifar-image-classifier",
      demo: true,
    },
    {
      id: "alpacabot-dashboard",
      title: "AlpacaBot Trading Dashboard",
      blurb: "Terminal-themed dashboard monitoring a weekly-options trading bot: positions, trades, and performance.",
      tech: ["JavaScript", "REST"],
      domains: ["data", "web"],
      repo: "https://github.com/sarvesh1karandikar/alpacabot-dashboard",
      demo: true,
    },
    {
      id: "1DotDev",
      title: "WhatsApp AI Assistant",
      blurb: "Production WhatsApp-native AI assistant on AWS Lightsail with per-user state, 17 slash-commands, and HMAC security.",
      tech: ["Node.js", "AWS", "SQLite"],
      domains: ["infra", "cloud"],
      repo: "https://github.com/sarvesh1karandikar/1DotDev",
      demo: true,
    },
    {
      id: "DriveSuite",
      title: "WhatsApp Media Bridge",
      blurb: "Bridges WhatsApp to a Jellyfin/Sonarr/Radarr media stack with local Llama + Claude model routing.",
      tech: ["Node.js", "Docker", "Ollama"],
      domains: ["infra"],
      repo: "https://github.com/sarvesh1karandikar/DriveSuite",
      demo: true,
    },
  ],
  skills: [
    { label: "Languages", items: ["Go", "Python", "Java", "C++", "GraphQL"] },
    { label: "Orchestration", items: ["Docker", "Kubernetes", "OCI", "Stacker"] },
    { label: "Cloud", items: ["AWS", "Azure", "GCP"] },
    { label: "Frameworks", items: ["TensorFlow", "PyTorch", "Pandas", "NumPy", "NLTK", "Terraform"] },
    { label: "Databases", items: ["Dgraph", "Postgres"] },
  ],
  education: [
    {
      school: "University of Southern California",
      degree: "M.S. Computer Science",
      end: "2020-05",
      coursework: ["Natural Language Processing", "Artificial Intelligence", "Machine Learning", "Deep Learning"],
    },
    {
      school: "SRM Institute of Science and Technology",
      degree: "B.Tech Computer Science and Engineering",
      end: "2018-05",
      coursework: ["Digital Image Processing", "Neural Networks", "Decision Support Systems", "Expert Systems using AI"],
    },
  ],
  contact: {
    email: "sarvesh1karandikar@gmail.com",
    github: "https://github.com/sarvesh1karandikar",
    linkedin: "https://www.linkedin.com/in/sarveshkarandikar/",
  },
};
